prepare_datasets:
  train_size: 0.75
  test_size: 0.15
  seed: 221

train_rf:
  n_estimators: 100
  seed: 42

train_catboost:
  iterations: 10000
  depth: 5
  learning_rate: 0.001
  loss_function: 'Logloss'
  seed: 42

train_mlp:
  lr: 0.001
  batch_size: 1024
  num_epochs: 150

